### PR TITLE
Merge ign-plugin1 ➡️  gz-plugin2

### PR DESCRIPTION
**Pull request by scpeters**
# ➡️  Forward port

Port `ign-plugin1 ` ➡️  `gz-plugin2`

Branch comparison: https://github.com/ignitionrobotics/ign-plugin/compare/gz-plugin2...ign-plugin1

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by azeey — APPROVED** [review]

**Review by azeey — CHANGES_REQUESTED** [review]
This is missing the changes in Changelog.md

**Review by mjcarroll — APPROVED** [review]

**Comment by scpeters** [comment]
> This is missing the changes in Changelog.md

I typically update the Changelog when making a release. The [source_changelog.bash](https://github.com/gazebo-tooling/release-tools/blob/master/source-repo-scripts/source_changelog.bash) script will include pull requests that are merged forward, though it also includes the merge commits, which I typically delete.

**Comment by scpeters** [comment]
> > This is missing the changes in Changelog.md
> 
> I typically update the Changelog when making a release. The [source_changelog.bash](https://github.com/gazebo-tooling/release-tools/blob/master/source-repo-scripts/source_changelog.bash) script will include pull requests that are merged forward, though it also includes the merge commits, which I typically delete.

never mind, I see what you're referring to. I'm on it

**Comment by scpeters** [comment]
> This is missing the changes in Changelog.md

I believe this was already fixed on `gz-plugin2` by https://github.com/gazebosim/gz-plugin/pull/111

**Comment by azeey** [comment]
> > This is missing the changes in Changelog.md
> 
> I believe this was already fixed on `gz-plugin2` by #111

Got it. Thanks!

**Review by azeey — APPROVED** [review]

**Pull request merged**
