### PR TITLE
ign -> gz Namespace Migration : gz-plugin

### PR DESCRIPTION
**Pull request by methylDragon**
See https://github.com/gazebo-tooling/release-tools/issues/711
Supercedes https://github.com/gazebosim/gz-plugin/pull/75

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
LGTM with the changed migration file and 🟢 CI

**Comment by scpeters** [comment]
the `https://github.com/gazebosim/gz-plugin/tree/namespace_migration/core/include/ignition/plugin.hh` file is missing

**Comment by methylDragon** [comment]
> the [core/include/ignition/plugin.hh](https://github.com/gazebosim/gz-plugin/tree/namespace_migration/core/include/ignition/plugin.hh) file is missing

I see you added the commit on the narrowed branch, the changes have been reflected here!

**Comment by scpeters** [comment]
> > the [core/include/ignition/plugin.hh](https://github.com/gazebosim/gz-plugin/tree/namespace_migration/core/include/ignition/plugin.hh) file is missing
> 
> I see you added the commit on the narrowed branch, the changes have been reflected here!

by the time this was merged, the file was lost again:

* https://github.com/gazebosim/gz-plugin/tree/main/core/include/ignition/plugin.hh

**Comment by methylDragon** [comment]
> > > the [core/include/ignition/plugin.hh](https://github.com/gazebosim/gz-plugin/tree/namespace_migration/core/include/ignition/plugin.hh) file is missing
> > 
> > 
> > I see you added the commit on the narrowed branch, the changes have been reflected here!
> 
> by the time this was merged, the file was lost again:
> 
> * https://github.com/gazebosim/gz-plugin/tree/main/core/include/ignition/plugin.hh

How did that happen :exploding_head: 
https://github.com/gazebosim/gz-plugin/pull/86

**Pull request merged**
